# Generated by Django 3.2.16 on 2022-11-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0003_message_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
