# Generated by Django 3.2.16 on 2022-11-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0004_remove_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='filename',
            field=models.UUIDField(default=None),
        ),
    ]
