# Generated by Django 3.2.16 on 2022-11-10 22:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0005_auto_20221110_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='filename',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
