# Generated by Django 3.2.16 on 2022-11-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0007_alter_message_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default='hello world'),
            preserve_default=False,
        ),
    ]
