# Generated by Django 3.2.16 on 2022-11-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0008_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
