# Generated by Django 3.2.15 on 2022-08-28 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0009_room_audio_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='audio_filename',
        ),
        migrations.AddField(
            model_name='room',
            name='audio_file_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='audio_file_creator',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
