# Generated by Django 3.2.16 on 2022-11-16 22:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("blabhear", "0010_alter_message_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="temp_id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
