# Generated by Django 3.2.15 on 2022-08-29 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0010_auto_20220828_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='audio_uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_uploading_audio', to=settings.AUTH_USER_MODEL),
        ),
    ]
