# Generated by Django 3.2.16 on 2022-11-16 22:15
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Message = apps.get_model("blabhear", "Message")
    for row in Message.objects.all():
        row.temp_id = uuid.uuid4()
        row.save(update_fields=["temp_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("blabhear", "0011_message_temp_id"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
