# Generated by Django 3.2.16 on 2022-11-16 22:15
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blabhear", "0012_auto_20221116_2215"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="temp_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
