# Generated by Django 3.2.16 on 2022-11-16 22:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0013_auto_20221116_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
