# Generated by Django 3.2.16 on 2022-11-16 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0016_rename_temp_id_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='id',
            new_name='temp_id',
        ),
    ]
