# Generated by Django 3.2.16 on 2022-11-16 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0017_rename_id_message_temp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
    ]
