# Generated by Django 3.2.16 on 2022-11-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0021_rename_temp_id_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
