# Generated by Django 3.2.16 on 2023-01-01 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0022_message_edited_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('zh', 'Chinese'), ('zh-CN', 'Chinese China'), ('zh-TW', 'Chinese Taiwan'), ('da', 'Danish'), ('nl', 'Dutch'), ('en', 'English'), ('en-AU', 'English Australia'), ('en-GB', 'English United Kingdom'), ('en-IN', 'English India'), ('en-NZ', 'English New Zealand'), ('en-US', 'English United States'), ('fr', 'French'), ('fr-CA', 'French Canada'), ('de', 'German'), ('hi', 'Hindi'), ('hi-Latn', 'Hindi Roman Script'), ('id', 'Indonesian'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('no', 'Norwegian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-BR', 'Portuguese Brazil'), ('pt-PT', 'Portuguese Portugal'), ('ru', 'Russian'), ('es', 'Spanish'), ('es-419', 'Spanish Latin America'), ('sv', 'Swedish'), ('ta', 'Tamil'), ('tr', 'Turkish'), ('uk', 'Ukrainian')], default='en', max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blabhear.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
