# Generated by Django 3.2.16 on 2023-01-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0023_recordingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordingsettings',
            name='language',
            field=models.CharField(choices=[('zh', 'Chinese'), ('zh-CN', 'Chinese China'), ('zh-TW', 'Chinese Taiwan'), ('da', 'Danish'), ('nl', 'Dutch Flemish'), ('en', 'English'), ('en-AU', 'English Australia'), ('en-GB', 'English United Kingdom'), ('en-IN', 'English India'), ('en-NZ', 'English New Zealand'), ('en-US', 'English United States'), ('fr', 'French'), ('fr-CA', 'French Canada'), ('de', 'German'), ('hi', 'Hindi'), ('hi-Latn', 'Hindi Roman Script'), ('id', 'Indonesian'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('no', 'Norwegian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-BR', 'Portuguese Brazil'), ('pt-PT', 'Portuguese Portugal'), ('ru', 'Russian'), ('es', 'Spanish'), ('es-419', 'Spanish Latin America'), ('sv', 'Swedish'), ('ta', 'Tamil'), ('tr', 'Turkish'), ('uk', 'Ukrainian')], default='en', max_length=10),
        ),
    ]
