# Generated by Django 3.2.16 on 2023-01-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0024_alter_recordingsettings_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingsettings',
            name='voice_effect',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
    ]
