LANGUAGES = [
    ("English", "en"),
    ("English (GB)", "en-GB"),
    ("English (US)", "en-US"),
    ("English (AU)", "en-AU"),
    ("English (IN)", "en-IN"),
    ("English (NZ)", "en-NZ"),
    ("French", "fr"),
    ("French (CA)", "fr-CA"),
    ("Ukrainian", "uk"),
    ("Spanish", "es"),
    ("Spanish (LatAm)", "es-419"),
    ("Turkish", "tr"),
    ("Tamil", "ta"),
    ("Swedish", "sv"),
    ("Russian", "ru"),
    ("Portuguese", "pt"),
    ("Portuguese (BR)", "pt-BR"),
    ("Portuguese (PT)", "pt-PT"),
    ("Polish", "pl"),
    ("Norwegian", "no"),
    ("Korean", "ko"),
    ("Japanese", "ja"),
    ("Italian", "it"),
    ("Indonesian", "id"),
    ("Hindi", "hi"),
    ("Hindi (Roman)", "hi-Latn"),
    ("German", "de"),
    ("Dutch/Flemish", "nl"),
    ("Danish", "da"),
    ("Chinese", "zh"),
    ("Chinese (CN)", "zh-CN"),
    ("Chinese (TW)", "zh-TW"),
]
