# Generated by Django 3.2.14 on 2022-08-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recblab', '0003_room_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
