# Generated by Django 3.2.15 on 2022-08-25 21:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recblab', '0008_room_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='audio_filename',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
