# Generated by Django 3.2.15 on 2022-08-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recblab', '0011_notification_audio_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
